---
apiVersion: v1
kind: ReplicationController
metadata:
  name: k8s-git-repo
  labels:
    app: k8s-git-repo
    version: v0.1
spec:
  replicas: 1
  selector:
    app: k8s-git-repo
    version: v0.1
  template:
    metadata:
      labels:
        app: k8s-git-repo
        version: v0.1
    spec:
      containers:
      - name: k8s-git-repo
        image: k8s-git-repo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 22
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-git-repo
  labels:
    app: k8s-git-repo
spec:
  selector:
    app: k8s-git-repo
  ports:
  - port: 22

# local variables:
# comment-start: "# "
# mode: shell-script
# end:
