#!/bin/bash
debug=0
dir=$(dirname $(readlink -f ${0}))
name=${dir##*/}
name=k8s-git-repo
yaml=${dir}/k8s-git-repo.yaml
inyaml=k8s-git-rc+svc-repo.yaml
. ${dir}/scripts/configure

# set -o errexit
set -o nounset
set -o pipefail

export KUBE_HOST_OS_USER=${os_user}
export KUBE_MASTER=${master}
export KUBECTL=${dir}/bin/kubectl
export KUBECONFIG=${dir}/.cfg/.${master}.cfg

# This script is using credentials sourced from .cfg/{master}
# generated by script/functions on first call which prompts for the
# cluster user and password and stores the credential in the config
# file.

. ${dir}/scripts/functions

if (( debug )); then
    rm -f ${yaml}
fi

KUBECTL="${KUBECTL} --kubeconfig=${KUBECONFIG}"

function make-yaml
{
    cat <<EOF
$(cat ${inyaml}|                                                                        \
  sed -r -e "s,namespace:.*k8s-git-repo.*,namespace: ${prefix}-k8s-git-repo,g"          \
         -e "s,app:.*k8s-git-repo.*,app: ${prefix}-k8s-git-repo,g"                      \
         -e "s,name:.*k8s-git-repo.*,name: ${prefix}-k8s-git-repo,g"                    \
         -e "s,authorized-keys:.*,authorized-keys: $(base64 -w 0 ~/.ssh/id_rsa.pub),g")
EOF
}

if (( debug )); then
   if [[ ! -e ${yaml} ]]; then
       make-yaml > ${yaml}
   fi
fi

chmod 700 . ${yaml}
chmod 600 ${yaml}

if ! [[ ${KUBECTL-} ]]; then
    echo Fix the location of the kubectl command
    exit 1
fi

function start
{
    ${KUBECTL} create -f- <<EOF
$(make-yaml)
EOF

}

function stop
{
    ${KUBECTL} delete -f- <<EOF
$(make-yaml)
EOF
}

function status
{
    ${KUBECTL} get --output=wide node
    ${KUBECTL} get --all-namespaces --output=wide rc,pods,svc,ep
}

function usage
{
    cat <<EOF

${0##*/} [--start|--stop|--status]

Run a private git repo in kubernetes with k8s secret from ssh keys
injected at create time from the user's ~/.ssh/id_rsa{,.pub} files.

EOF
    exit 3
}

function main
{
    if (( $# )) ; then
        for arg in ${@}; do
            case ${arg} in
                --start)
                    start
                    ;;
                --stop)
                    stop
                    ;;
                --status)
                    status
                    ;;
                *)
                    usage
            esac
        done
    else
        usage
    fi
    exit
}

main ${@}

# local variables:
# comment-start: "# "
# mode: shell-script
# end:
