apiVersion: v1
kind: Namespace
metadata:
  name: k8s-git-repo
---
apiVersion: v1
kind: ReplicationController
metadata:
  namespace: k8s-git-repo
  name: k8s-git-repo
  labels:
    app: k8s-git-repo
    version: v0.1
spec:
  replicas: 1
  selector:
    app: k8s-git-repo
    version: v0.1
  template:
    metadata:
      labels:
        app: k8s-git-repo
        version: v0.1
    spec:
      containers:
      - name: k8s-git-repo
        image: k8s-git-repo
        imagePullPolicy: IfNotPresent
        command: 
        - /bin/bash
        - -xc
        - |
          function clean
          {
             echo clean up begun
             rm -f /home/git/.ssh/*
             echo clean up done
          }

          trap clean EXIT KILL TERM INT
          while [[ ! -e /home/git/.private/authorized-keys ]]; do
              sleep 1;
          done;
          pushd /home/git/.private/

          chmod 700 *;
          chown git *;
          pushd /home/git/.ssh/
          for file in /home/git/.private/*; do
              name=${file//-/_}
              # If the secrets are copied then the dead container
              # exposes the secret. Since this is a public key, it
              # might be okay, but for getting into good habits. . .
              # soft link as the owner
              su -c "ln -sf ${file} ${name##*/}" git
          done;
          chmod -R 700 /home/git/{.private,.ssh} ;
          chown -R git /home/git/{.private,.ssh} ;

          echo Running sshd . . .
          /usr/sbin/sshd -D
          echo Exiting . . .
        ports:
        - containerPort: 22
        volumeMounts:
        - mountPath: /home/git/.private
          name: secret-volume
      volumes:
      - name: secret-volume
        secret:
          secretName: ssh-key-secret
---
apiVersion: v1
kind: Service
metadata:
  namespace: k8s-git-repo
  name: k8s-git-repo
  labels:
    app: k8s-git-repo
spec:
  selector:
    app: k8s-git-repo
  ports:
  - port: 22
