#!/bin/bash
debug=1
dir=$(dirname $(readlink -f ${0}))
name=${dir##*/}
name=k8s-git-repo
yaml=${dir}/k8s-git-repo.yaml
inyaml=k8s-git-rc+svc-repo.yaml
# set -o errexit
set -o nounset
set -o pipefail

# This script is using credentials sourced from .cfg/{master}
# generated by script/functions on first call which prompts for the
# cluster user and password and stores the credential in the config
# file.

. ${dir}/.cfg/functions

function make-yaml
{
  sed -r -e "s,namespace:.*k8s-git-repo.*,namespace: ${prefix}-k8s-git-repo,g"          \
         -e "s,app:.*k8s-git-repo.*,app: ${prefix}-k8s-git-repo,g"                      \
         -e "s,name:.*k8s-git-repo.*,name: ${prefix}-k8s-git-repo,g"                    \
         -e "s,authorized-keys:.*,authorized-keys: $(base64 -w 0 ~/.ssh/id_rsa.pub),g"  \
         ${inyaml}
}

if (( debug )); then
    rm -f ${yaml}
    if [[ ! -e ${yaml} ]]; then
        make-yaml > ${yaml}
    fi
    chmod 600 ${yaml}
fi

main ${@}

# local variables:
# comment-start: "# "
# mode: shell-script
# end:
