#!/bin/bash

function make-yaml
{
# if {repo} is used for a repo to auto inject then the following
# formula might be inserted for a sed replacement
#        -e "s,\{repo\}(.*),${k8stestrepo}\\1,g"

  sed -r -e "s,namespace:.*k8s-git-repo.*,namespace: ${prefix}-k8s-git-repo,g"                          \
         -e "s,app:.*k8s-git-repo.*,app: ${prefix}-k8s-git-repo,g"                                      \
         -e "s,name:.*k8s-git-repo.*,name: ${prefix}-k8s-git-repo,g"                                    \
         -e "s,authorized-keys:.*,authorized-keys: $(base64 -w 0 ~/.ssh/id_${ssh_key_type}.pub),g"      \
         ${inyaml}
}
