#!/bin/bash
function make-yaml-stdio
{
    if (( ! rename )); then
        local id=""
    fi
    public=$(base64 -w 0 ~/.ssh/id_${ssh_key_type}.pub)
    private=$(base64 -w 0 ~/.ssh/id_${ssh_key_type})
    sed -r                                                                              \
        -e "s,\{repo\}(.*),${k8stestrepo}\\1,g"                                         \
        -e "s,app:.*${name}.*,app: ${id}${name},g"                                      \
        -e "s,namespace:.*${name}.*,namespace: ${id}${name},g"                          \
        -e "s,secretName: *${name}-secret *\$,secretName: ${id}${name}-secret,g"        \
        -e "s,name: *${name}-secret,name: ${id}${name}-secret,g"                        \
        -e "s,name: *${name} *\$,name: ${id}${name},g"                                  \
        -e "s,authorized-keys:.*,authorized-keys: ${public},g"                          \
        -e "s,id-:.*,id-${ssh_key_type}: ${private},g"                                  \
        -e "s,id-.pub:.*,id-${ssh_key_type}.pub: ${public},g"
}

function make-yaml-call
{
    local inyaml=${1}
    make-yaml-stdio < ${inyaml}
}

function make-yaml
{
    make-yaml-call ${inyaml}
}
